"""deleted

Revision ID: d2d0fe436605
Revises: 
Create Date: 2026-09-09 10:28:42.166157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d0fe436605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_man', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('is_man')

    # ### end Alembic commands ###
