"""added

Revision ID: d3a7839eaa65
Revises: e5d84fb119ab
Create Date: 2026-09-09 21:18:49.241763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a7839eaa65'
down_revision = 'e5d84fb119ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.drop_column('is_popular')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_popular', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
