"""added

Revision ID: e5d84fb119ab
Revises: d2d0fe436605
Create Date: 2026-09-09 10:38:27.110783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d84fb119ab'
down_revision = 'd2d0fe436605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('is_man')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_comp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('is_comp')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_man', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
